/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends org.jooq.impl.UpdatableRecordImpl<org.kallithea.ldap.sync.jooq.tables.records.GroupsRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = 1399411018;

	/**
	 * Setter for <code>public.groups.group_id</code>.
	 */
	public void setGroupId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.groups.group_id</code>.
	 */
	public java.lang.Integer getGroupId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.groups.group_name</code>.
	 */
	public void setGroupName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.groups.group_name</code>.
	 */
	public java.lang.String getGroupName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.groups.group_parent_id</code>.
	 */
	public void setGroupParentId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.groups.group_parent_id</code>.
	 */
	public java.lang.Integer getGroupParentId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.groups.group_description</code>.
	 */
	public void setGroupDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.groups.group_description</code>.
	 */
	public java.lang.String getGroupDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.groups.enable_locking</code>.
	 */
	public void setEnableLocking(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.groups.enable_locking</code>.
	 */
	public java.lang.Boolean getEnableLocking() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.groups.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.groups.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.groups.created_on</code>.
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.groups.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.GROUP_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.GROUP_PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.GROUP_DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.ENABLE_LOCKING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGroupName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getGroupParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getGroupDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getEnableLocking();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreatedOn();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupsRecord
	 */
	public GroupsRecord() {
		super(org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS);
	}

	/**
	 * Create a detached, initialised GroupsRecord
	 */
	public GroupsRecord(java.lang.Integer groupId, java.lang.String groupName, java.lang.Integer groupParentId, java.lang.String groupDescription, java.lang.Boolean enableLocking, java.lang.Integer userId, java.sql.Timestamp createdOn) {
		super(org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS);

		setValue(0, groupId);
		setValue(1, groupName);
		setValue(2, groupParentId);
		setValue(3, groupDescription);
		setValue(4, enableLocking);
		setValue(5, userId);
		setValue(6, createdOn);
	}
}
