/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullRequestsRecord extends org.jooq.impl.UpdatableRecordImpl<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord> implements org.jooq.Record12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1870924166;

	/**
	 * Setter for <code>public.pull_requests.pull_request_id</code>.
	 */
	public void setPullRequestId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.pull_requests.pull_request_id</code>.
	 */
	public java.lang.Integer getPullRequestId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.pull_requests.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.pull_requests.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.pull_requests.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.pull_requests.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.pull_requests.status</code>.
	 */
	public void setStatus(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.pull_requests.status</code>.
	 */
	public java.lang.String getStatus() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.pull_requests.created_on</code>.
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.pull_requests.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.pull_requests.updated_on</code>.
	 */
	public void setUpdatedOn(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.pull_requests.updated_on</code>.
	 */
	public java.sql.Timestamp getUpdatedOn() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>public.pull_requests.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.pull_requests.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.pull_requests.revisions</code>.
	 */
	public void setRevisions(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.pull_requests.revisions</code>.
	 */
	public java.lang.String getRevisions() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.pull_requests.org_repo_id</code>.
	 */
	public void setOrgRepoId(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.pull_requests.org_repo_id</code>.
	 */
	public java.lang.Integer getOrgRepoId() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>public.pull_requests.org_ref</code>.
	 */
	public void setOrgRef(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.pull_requests.org_ref</code>.
	 */
	public java.lang.String getOrgRef() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.pull_requests.other_repo_id</code>.
	 */
	public void setOtherRepoId(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.pull_requests.other_repo_id</code>.
	 */
	public java.lang.Integer getOtherRepoId() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>public.pull_requests.other_ref</code>.
	 */
	public void setOtherRef(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.pull_requests.other_ref</code>.
	 */
	public java.lang.String getOtherRef() {
		return (java.lang.String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.PULL_REQUEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.UPDATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.REVISIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.ORG_REPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.ORG_REF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.OTHER_REPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS.OTHER_REF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getPullRequestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getUpdatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getRevisions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getOrgRepoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getOrgRef();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getOtherRepoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getOtherRef();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PullRequestsRecord
	 */
	public PullRequestsRecord() {
		super(org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS);
	}

	/**
	 * Create a detached, initialised PullRequestsRecord
	 */
	public PullRequestsRecord(java.lang.Integer pullRequestId, java.lang.String title, java.lang.String description, java.lang.String status, java.sql.Timestamp createdOn, java.sql.Timestamp updatedOn, java.lang.Integer userId, java.lang.String revisions, java.lang.Integer orgRepoId, java.lang.String orgRef, java.lang.Integer otherRepoId, java.lang.String otherRef) {
		super(org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS);

		setValue(0, pullRequestId);
		setValue(1, title);
		setValue(2, description);
		setValue(3, status);
		setValue(4, createdOn);
		setValue(5, updatedOn);
		setValue(6, userId);
		setValue(7, revisions);
		setValue(8, orgRepoId);
		setValue(9, orgRef);
		setValue(10, otherRepoId);
		setValue(11, otherRef);
	}
}
