/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserApiKeysRecord extends org.jooq.impl.UpdatableRecordImpl<org.kallithea.ldap.sync.jooq.tables.records.UserApiKeysRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Timestamp> {

	private static final long serialVersionUID = 1034868355;

	/**
	 * Setter for <code>public.user_api_keys.user_api_key_id</code>.
	 */
	public void setUserApiKeyId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.user_api_key_id</code>.
	 */
	public java.lang.Integer getUserApiKeyId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.user_api_keys.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.user_api_keys.api_key</code>.
	 */
	public void setApiKey(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.api_key</code>.
	 */
	public java.lang.String getApiKey() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.user_api_keys.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.user_api_keys.expires</code>.
	 */
	public void setExpires(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.expires</code>.
	 */
	public java.lang.Double getExpires() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>public.user_api_keys.created_on</code>.
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.user_api_keys.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Double, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.USER_API_KEY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.API_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.EXPIRES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserApiKeyId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getApiKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getExpires();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreatedOn();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserApiKeysRecord
	 */
	public UserApiKeysRecord() {
		super(org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS);
	}

	/**
	 * Create a detached, initialised UserApiKeysRecord
	 */
	public UserApiKeysRecord(java.lang.Integer userApiKeyId, java.lang.Integer userId, java.lang.String apiKey, java.lang.String description, java.lang.Double expires, java.sql.Timestamp createdOn) {
		super(org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS);

		setValue(0, userApiKeyId);
		setValue(1, userId);
		setValue(2, apiKey);
		setValue(3, description);
		setValue(4, expires);
		setValue(5, createdOn);
	}
}
