/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersGroupsRecord extends org.jooq.impl.UpdatableRecordImpl<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupsRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp, byte[]> {

	private static final long serialVersionUID = 24072974;

	/**
	 * Setter for <code>public.users_groups.users_group_id</code>.
	 */
	public void setUsersGroupId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users_groups.users_group_id</code>.
	 */
	public java.lang.Integer getUsersGroupId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.users_groups.users_group_name</code>.
	 */
	public void setUsersGroupName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users_groups.users_group_name</code>.
	 */
	public java.lang.String getUsersGroupName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.users_groups.user_group_description</code>.
	 */
	public void setUserGroupDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users_groups.user_group_description</code>.
	 */
	public java.lang.String getUserGroupDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.users_groups.users_group_active</code>.
	 */
	public void setUsersGroupActive(java.lang.Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.users_groups.users_group_active</code>.
	 */
	public java.lang.Boolean getUsersGroupActive() {
		return (java.lang.Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.users_groups.users_group_inherit_default_permissions</code>.
	 */
	public void setUsersGroupInheritDefaultPermissions(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.users_groups.users_group_inherit_default_permissions</code>.
	 */
	public java.lang.Boolean getUsersGroupInheritDefaultPermissions() {
		return (java.lang.Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.users_groups.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.users_groups.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.users_groups.created_on</code>.
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.users_groups.created_on</code>.
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.users_groups.group_data</code>.
	 */
	public void setGroupData(byte[] value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.users_groups.group_data</code>.
	 */
	public byte[] getGroupData() {
		return (byte[]) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp, byte[]> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Integer, java.sql.Timestamp, byte[]> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USERS_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USERS_GROUP_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USER_GROUP_DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field4() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USERS_GROUP_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USERS_GROUP_INHERIT_DEFAULT_PERMISSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field8() {
		return org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS.GROUP_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUsersGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUsersGroupName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUserGroupDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value4() {
		return getUsersGroupActive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getUsersGroupInheritDefaultPermissions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value8() {
		return getGroupData();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersGroupsRecord
	 */
	public UsersGroupsRecord() {
		super(org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS);
	}

	/**
	 * Create a detached, initialised UsersGroupsRecord
	 */
	public UsersGroupsRecord(java.lang.Integer usersGroupId, java.lang.String usersGroupName, java.lang.String userGroupDescription, java.lang.Boolean usersGroupActive, java.lang.Boolean usersGroupInheritDefaultPermissions, java.lang.Integer userId, java.sql.Timestamp createdOn, byte[] groupData) {
		super(org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS);

		setValue(0, usersGroupId);
		setValue(1, usersGroupName);
		setValue(2, userGroupDescription);
		setValue(3, usersGroupActive);
		setValue(4, usersGroupInheritDefaultPermissions);
		setValue(5, userId);
		setValue(6, createdOn);
		setValue(7, groupData);
	}
}
