/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1123005537;

	/**
	 * The singleton instance of <code>public</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("public");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(org.kallithea.ldap.sync.jooq.Sequences.CACHE_INVALIDATION_CACHE_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.CHANGESET_COMMENTS_COMMENT_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.CHANGESET_STATUSES_CHANGESET_STATUS_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.GISTS_GIST_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.GROUPS_GROUP_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.NOTIFICATIONS_NOTIFICATION_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.PERMISSIONS_PERMISSION_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.PULL_REQUEST_REVIEWERS_PULL_REQUESTS_REVIEWERS_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.PULL_REQUESTS_PULL_REQUEST_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.REPOSITORIES_FIELDS_REPO_FIELD_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.REPOSITORIES_REPO_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.REPO_TO_PERM_REPO_TO_PERM_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.SETTINGS_APP_SETTINGS_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.STATISTICS_STAT_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.UI_UI_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_API_KEYS_USER_API_KEY_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_EMAIL_MAP_EMAIL_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_FOLLOWINGS_USER_FOLLOWING_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_GROUP_USER_GROUP_TO_PERM_USER_GROUP_USER_GROUP_TO_PERM_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_IP_MAP_IP_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_LOGS_USER_LOG_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_REPO_GROUP_TO_PERM_GROUP_TO_PERM_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_GROUP_REPO_GROUP_TO_PER_USERS_GROUP_REPO_GROUP_TO_PER_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_GROUP_REPO_TO_PERM_USERS_GROUP_TO_PERM_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_GROUPS_MEMBERS_USERS_GROUP_MEMBER_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_GROUPS_USERS_GROUP_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_GROUP_TO_PERM_USERS_GROUP_TO_PERM_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USERS_USER_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_TO_PERM_USER_TO_PERM_ID_SEQ,
			org.kallithea.ldap.sync.jooq.Sequences.USER_USER_GROUP_TO_PERM_USER_USER_GROUP_TO_PERM_ID_SEQ);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(org.kallithea.ldap.sync.jooq.tables.CacheInvalidation.CACHE_INVALIDATION,
			org.kallithea.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS,
			org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses.CHANGESET_STATUSES,
			org.kallithea.ldap.sync.jooq.tables.DbMigrateVersion.DB_MIGRATE_VERSION,
			org.kallithea.ldap.sync.jooq.tables.Gists.GISTS,
			org.kallithea.ldap.sync.jooq.tables.Groups.GROUPS,
			org.kallithea.ldap.sync.jooq.tables.Notifications.NOTIFICATIONS,
			org.kallithea.ldap.sync.jooq.tables.Permissions.PERMISSIONS,
			org.kallithea.ldap.sync.jooq.tables.PullRequestReviewers.PULL_REQUEST_REVIEWERS,
			org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS,
			org.kallithea.ldap.sync.jooq.tables.Repositories.REPOSITORIES,
			org.kallithea.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS,
			org.kallithea.ldap.sync.jooq.tables.RepoToPerm.REPO_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.Settings.SETTINGS,
			org.kallithea.ldap.sync.jooq.tables.Statistics.STATISTICS,
			org.kallithea.ldap.sync.jooq.tables.Ui.UI,
			org.kallithea.ldap.sync.jooq.tables.UserApiKeys.USER_API_KEYS,
			org.kallithea.ldap.sync.jooq.tables.UserEmailMap.USER_EMAIL_MAP,
			org.kallithea.ldap.sync.jooq.tables.UserFollowings.USER_FOLLOWINGS,
			org.kallithea.ldap.sync.jooq.tables.UserGroupUserGroupToPerm.USER_GROUP_USER_GROUP_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.UserIpMap.USER_IP_MAP,
			org.kallithea.ldap.sync.jooq.tables.UserLogs.USER_LOGS,
			org.kallithea.ldap.sync.jooq.tables.UserRepoGroupToPerm.USER_REPO_GROUP_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.Users.USERS,
			org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm.USERS_GROUP_REPO_GROUP_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm.USERS_GROUP_REPO_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.UsersGroups.USERS_GROUPS,
			org.kallithea.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS,
			org.kallithea.ldap.sync.jooq.tables.UsersGroupToPerm.USERS_GROUP_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION,
			org.kallithea.ldap.sync.jooq.tables.UserToPerm.USER_TO_PERM,
			org.kallithea.ldap.sync.jooq.tables.UserUserGroupToPerm.USER_USER_GROUP_TO_PERM);
	}
}
