/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangesetStatuses extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord> {

	private static final long serialVersionUID = 1502712620;

	/**
	 * The singleton instance of <code>public.changeset_statuses</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses CHANGESET_STATUSES = new org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord.class;
	}

	/**
	 * The column <code>public.changeset_statuses.changeset_status_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> CHANGESET_STATUS_ID = createField("changeset_status_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.changeset_statuses.repo_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> REPO_ID = createField("repo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.revision</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.String> REVISION = createField("revision", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.status</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.changeset_comment_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> CHANGESET_COMMENT_ID = createField("changeset_comment_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.changeset_statuses.modified_at</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.sql.Timestamp> MODIFIED_AT = createField("modified_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.version</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.changeset_statuses.pull_request_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> PULL_REQUEST_ID = createField("pull_request_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.changeset_statuses</code> table reference
	 */
	public ChangesetStatuses() {
		super("changeset_statuses", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.changeset_statuses</code> table reference
	 */
	public ChangesetStatuses(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses.CHANGESET_STATUSES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_CHANGESET_STATUSES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES_PKEY, org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES_REPO_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.ChangesetStatusesRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES__CHANGESET_STATUSES_REPO_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES__CHANGESET_STATUSES_USER_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES__CHANGESET_STATUSES_CHANGESET_COMMENT_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.CHANGESET_STATUSES__CHANGESET_STATUSES_PULL_REQUEST_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.ChangesetStatuses(alias);
	}
}
