/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gists extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord> {

	private static final long serialVersionUID = -1850394689;

	/**
	 * The singleton instance of <code>public.gists</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.Gists GISTS = new org.kallithea.ldap.sync.jooq.tables.Gists();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.GistsRecord.class;
	}

	/**
	 * The column <code>public.gists.gist_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.Integer> GIST_ID = createField("gist_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.gists.gist_access_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.String> GIST_ACCESS_ID = createField("gist_access_id", org.jooq.impl.SQLDataType.VARCHAR.length(250), this);

	/**
	 * The column <code>public.gists.gist_description</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.String> GIST_DESCRIPTION = createField("gist_description", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>public.gists.user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.gists.gist_expires</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.Double> GIST_EXPIRES = createField("gist_expires", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this);

	/**
	 * The column <code>public.gists.gist_type</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.String> GIST_TYPE = createField("gist_type", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this);

	/**
	 * The column <code>public.gists.created_on</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>public.gists.modified_at</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.sql.Timestamp> MODIFIED_AT = createField("modified_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * Create a <code>public.gists</code> table reference
	 */
	public Gists() {
		super("gists", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.gists</code> table reference
	 */
	public Gists(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.Gists.GISTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_GISTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.GISTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.GISTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.GistsRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.GISTS__GISTS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.Gists as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.Gists(alias);
	}
}
