/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notifications extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord> {

	private static final long serialVersionUID = -153780923;

	/**
	 * The singleton instance of <code>public.notifications</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.Notifications NOTIFICATIONS = new org.kallithea.ldap.sync.jooq.tables.Notifications();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord.class;
	}

	/**
	 * The column <code>public.notifications.notification_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.Integer> NOTIFICATION_ID = createField("notification_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.notifications.subject</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.String> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.VARCHAR.length(512), this);

	/**
	 * The column <code>public.notifications.body</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.String> BODY = createField("body", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>public.notifications.created_by</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.Integer> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.notifications.created_on</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>public.notifications.type</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.notifications</code> table reference
	 */
	public Notifications() {
		super("notifications", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.notifications</code> table reference
	 */
	public Notifications(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.Notifications.NOTIFICATIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_NOTIFICATIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.NOTIFICATIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.NOTIFICATIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.NotificationsRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.NOTIFICATIONS__NOTIFICATIONS_CREATED_BY_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.Notifications as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.Notifications(alias);
	}
}
