/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permissions extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord> {

	private static final long serialVersionUID = 484769312;

	/**
	 * The singleton instance of <code>public.permissions</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.Permissions PERMISSIONS = new org.kallithea.ldap.sync.jooq.tables.Permissions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord.class;
	}

	/**
	 * The column <code>public.permissions.permission_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.permissions.permission_name</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord, java.lang.String> PERMISSION_NAME = createField("permission_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.permissions.permission_longname</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord, java.lang.String> PERMISSION_LONGNAME = createField("permission_longname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.permissions</code> table reference
	 */
	public Permissions() {
		super("permissions", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.permissions</code> table reference
	 */
	public Permissions(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.Permissions.PERMISSIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_PERMISSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.PERMISSIONS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PermissionsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.PERMISSIONS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.Permissions as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.Permissions(alias);
	}
}
