/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullRequests extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord> {

	private static final long serialVersionUID = 53960403;

	/**
	 * The singleton instance of <code>public.pull_requests</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.PullRequests PULL_REQUESTS = new org.kallithea.ldap.sync.jooq.tables.PullRequests();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord.class;
	}

	/**
	 * The column <code>public.pull_requests.pull_request_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.Integer> PULL_REQUEST_ID = createField("pull_request_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.pull_requests.title</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.pull_requests.description</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>public.pull_requests.status</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>public.pull_requests.created_on</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>public.pull_requests.updated_on</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.sql.Timestamp> UPDATED_ON = createField("updated_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>public.pull_requests.user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.pull_requests.revisions</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> REVISIONS = createField("revisions", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>public.pull_requests.org_repo_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.Integer> ORG_REPO_ID = createField("org_repo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.pull_requests.org_ref</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> ORG_REF = createField("org_ref", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>public.pull_requests.other_repo_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.Integer> OTHER_REPO_ID = createField("other_repo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.pull_requests.other_ref</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.String> OTHER_REF = createField("other_ref", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>public.pull_requests</code> table reference
	 */
	public PullRequests() {
		super("pull_requests", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.pull_requests</code> table reference
	 */
	public PullRequests(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.PullRequests.PULL_REQUESTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_PULL_REQUESTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.PULL_REQUESTS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.PULL_REQUESTS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.PullRequestsRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.PULL_REQUESTS__PULL_REQUESTS_USER_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.PULL_REQUESTS__PULL_REQUESTS_ORG_REPO_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.PULL_REQUESTS__PULL_REQUESTS_OTHER_REPO_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.PullRequests as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.PullRequests(alias);
	}
}
