/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord> {

	private static final long serialVersionUID = 1301289278;

	/**
	 * The singleton instance of <code>public.settings</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.Settings SETTINGS = new org.kallithea.ldap.sync.jooq.tables.Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord.class;
	}

	/**
	 * The column <code>public.settings.app_settings_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord, java.lang.Integer> APP_SETTINGS_ID = createField("app_settings_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.settings.app_settings_name</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord, java.lang.String> APP_SETTINGS_NAME = createField("app_settings_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.settings.app_settings_value</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord, java.lang.String> APP_SETTINGS_VALUE = createField("app_settings_value", org.jooq.impl.SQLDataType.VARCHAR.length(4096), this);

	/**
	 * The column <code>public.settings.app_settings_type</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord, java.lang.String> APP_SETTINGS_TYPE = createField("app_settings_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.settings</code> table reference
	 */
	public Settings() {
		super("settings", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.settings</code> table reference
	 */
	public Settings(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.Settings.SETTINGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_SETTINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.SettingsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.SETTINGS_PKEY, org.kallithea.ldap.sync.jooq.Keys.SETTINGS_APP_SETTINGS_NAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.Settings as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.Settings(alias);
	}
}
