/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserFollowings extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord> {

	private static final long serialVersionUID = -87963529;

	/**
	 * The singleton instance of <code>public.user_followings</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.UserFollowings USER_FOLLOWINGS = new org.kallithea.ldap.sync.jooq.tables.UserFollowings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord.class;
	}

	/**
	 * The column <code>public.user_followings.user_following_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.lang.Integer> USER_FOLLOWING_ID = createField("user_following_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_followings.user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_followings.follows_repository_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.lang.Integer> FOLLOWS_REPOSITORY_ID = createField("follows_repository_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.user_followings.follows_user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.lang.Integer> FOLLOWS_USER_ID = createField("follows_user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.user_followings.follows_from</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.sql.Timestamp> FOLLOWS_FROM = createField("follows_from", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>public.user_followings</code> table reference
	 */
	public UserFollowings() {
		super("user_followings", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_followings</code> table reference
	 */
	public UserFollowings(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.UserFollowings.USER_FOLLOWINGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_USER_FOLLOWINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS_PKEY, org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS_USER_ID_KEY, org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS_USER_ID_KEY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UserFollowingsRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS__USER_FOLLOWINGS_USER_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS__USER_FOLLOWINGS_FOLLOWS_REPOSITORY_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.USER_FOLLOWINGS__USER_FOLLOWINGS_FOLLOWS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.UserFollowings as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.UserFollowings(alias);
	}
}
