/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersGroupRepoToPerm extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord> {

	private static final long serialVersionUID = -76018485;

	/**
	 * The singleton instance of <code>public.users_group_repo_to_perm</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm USERS_GROUP_REPO_TO_PERM = new org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord.class;
	}

	/**
	 * The column <code>public.users_group_repo_to_perm.users_group_to_perm_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, java.lang.Integer> USERS_GROUP_TO_PERM_ID = createField("users_group_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.users_group_repo_to_perm.users_group_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, java.lang.Integer> USERS_GROUP_ID = createField("users_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.users_group_repo_to_perm.permission_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.users_group_repo_to_perm.repository_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, java.lang.Integer> REPOSITORY_ID = createField("repository_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.users_group_repo_to_perm</code> table reference
	 */
	public UsersGroupRepoToPerm() {
		super("users_group_repo_to_perm", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.users_group_repo_to_perm</code> table reference
	 */
	public UsersGroupRepoToPerm(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm.USERS_GROUP_REPO_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_USERS_GROUP_REPO_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM_PKEY, org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM_REPOSITORY_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UsersGroupRepoToPermRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM__USERS_GROUP_REPO_TO_PERM_USERS_GROUP_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM__USERS_GROUP_REPO_TO_PERM_PERMISSION_ID_FKEY, org.kallithea.ldap.sync.jooq.Keys.USERS_GROUP_REPO_TO_PERM__USERS_GROUP_REPO_TO_PERM_REPOSITORY_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.UsersGroupRepoToPerm(alias);
	}
}
