/**
 * This class is generated by jOOQ
 */
package org.kallithea.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEmailMap extends org.jooq.impl.TableImpl<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord> {

	private static final long serialVersionUID = -2005690018;

	/**
	 * The singleton instance of <code>public.user_email_map</code>
	 */
	public static final org.kallithea.ldap.sync.jooq.tables.UserEmailMap USER_EMAIL_MAP = new org.kallithea.ldap.sync.jooq.tables.UserEmailMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord> getRecordType() {
		return org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord.class;
	}

	/**
	 * The column <code>public.user_email_map.email_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, java.lang.Integer> EMAIL_ID = createField("email_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_email_map.user_id</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.user_email_map.email</code>.
	 */
	public final org.jooq.TableField<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.user_email_map</code> table reference
	 */
	public UserEmailMap() {
		super("user_email_map", org.kallithea.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_email_map</code> table reference
	 */
	public UserEmailMap(java.lang.String alias) {
		super(alias, org.kallithea.ldap.sync.jooq.Public.PUBLIC, org.kallithea.ldap.sync.jooq.tables.UserEmailMap.USER_EMAIL_MAP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, java.lang.Integer> getIdentity() {
		return org.kallithea.ldap.sync.jooq.Keys.IDENTITY_USER_EMAIL_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord> getPrimaryKey() {
		return org.kallithea.ldap.sync.jooq.Keys.USER_EMAIL_MAP_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord>>asList(org.kallithea.ldap.sync.jooq.Keys.USER_EMAIL_MAP_PKEY, org.kallithea.ldap.sync.jooq.Keys.USER_EMAIL_MAP_EMAIL_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.kallithea.ldap.sync.jooq.tables.records.UserEmailMapRecord, ?>>asList(org.kallithea.ldap.sync.jooq.Keys.USER_EMAIL_MAP__USER_EMAIL_MAP_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.kallithea.ldap.sync.jooq.tables.UserEmailMap as(java.lang.String alias) {
		return new org.kallithea.ldap.sync.jooq.tables.UserEmailMap(alias);
	}
}
