/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord> {

	private static final long serialVersionUID = -1912271030;

	/**
	 * The singleton instance of <code>public.groups</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.Groups GROUPS = new org.rhodecode.ldap.sync.jooq.tables.Groups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord.class;
	}

	/**
	 * The column <code>public.groups.group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.groups.group_name</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.String> GROUP_NAME = createField("group_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * The column <code>public.groups.group_parent_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.Integer> GROUP_PARENT_ID = createField("group_parent_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.groups.group_description</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.String> GROUP_DESCRIPTION = createField("group_description", org.jooq.impl.SQLDataType.VARCHAR.length(10000), this);

	/**
	 * The column <code>public.groups.enable_locking</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.Boolean> ENABLE_LOCKING = createField("enable_locking", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this);

	/**
	 * The column <code>public.groups.user_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.groups.created_on</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.sql.Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * Create a <code>public.groups</code> table reference
	 */
	public Groups() {
		super("groups", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.groups</code> table reference
	 */
	public Groups(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.Groups.GROUPS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_GROUPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.GROUPS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.GROUPS_PKEY, org.rhodecode.ldap.sync.jooq.Keys.GROUPS_GROUP_NAME_KEY, org.rhodecode.ldap.sync.jooq.Keys.GROUPS_GROUP_NAME_KEY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.GroupsRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.GROUPS__GROUPS_GROUP_PARENT_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.GROUPS__GROUPS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.Groups as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.Groups(alias);
	}
}
