/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PullRequestReviewers extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord> {

	private static final long serialVersionUID = -298913729;

	/**
	 * The singleton instance of <code>public.pull_request_reviewers</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.PullRequestReviewers PULL_REQUEST_REVIEWERS = new org.rhodecode.ldap.sync.jooq.tables.PullRequestReviewers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord.class;
	}

	/**
	 * The column <code>public.pull_request_reviewers.pull_requests_reviewers_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, java.lang.Integer> PULL_REQUESTS_REVIEWERS_ID = createField("pull_requests_reviewers_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.pull_request_reviewers.pull_request_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, java.lang.Integer> PULL_REQUEST_ID = createField("pull_request_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.pull_request_reviewers.user_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>public.pull_request_reviewers</code> table reference
	 */
	public PullRequestReviewers() {
		super("pull_request_reviewers", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.pull_request_reviewers</code> table reference
	 */
	public PullRequestReviewers(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.PullRequestReviewers.PULL_REQUEST_REVIEWERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_PULL_REQUEST_REVIEWERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.PULL_REQUEST_REVIEWERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.PULL_REQUEST_REVIEWERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.PullRequestReviewersRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.PULL_REQUEST_REVIEWERS__PULL_REQUEST_REVIEWERS_PULL_REQUEST_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.PULL_REQUEST_REVIEWERS__PULL_REQUEST_REVIEWERS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.PullRequestReviewers as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.PullRequestReviewers(alias);
	}
}
