/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepoToPerm extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord> {

	private static final long serialVersionUID = 365504560;

	/**
	 * The singleton instance of <code>public.repo_to_perm</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.RepoToPerm REPO_TO_PERM = new org.rhodecode.ldap.sync.jooq.tables.RepoToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord.class;
	}

	/**
	 * The column <code>public.repo_to_perm.repo_to_perm_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, java.lang.Integer> REPO_TO_PERM_ID = createField("repo_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.repo_to_perm.user_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.repo_to_perm.permission_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.repo_to_perm.repository_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, java.lang.Integer> REPOSITORY_ID = createField("repository_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.repo_to_perm</code> table reference
	 */
	public RepoToPerm() {
		super("repo_to_perm", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.repo_to_perm</code> table reference
	 */
	public RepoToPerm(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.RepoToPerm.REPO_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_REPO_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM_PKEY, org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM_USER_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.RepoToPermRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM__REPO_TO_PERM_USER_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM__REPO_TO_PERM_PERMISSION_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.REPO_TO_PERM__REPO_TO_PERM_REPOSITORY_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.RepoToPerm as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.RepoToPerm(alias);
	}
}
