/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RhodecodeSettings extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord> {

	private static final long serialVersionUID = 1179494954;

	/**
	 * The singleton instance of <code>public.rhodecode_settings</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.RhodecodeSettings RHODECODE_SETTINGS = new org.rhodecode.ldap.sync.jooq.tables.RhodecodeSettings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord.class;
	}

	/**
	 * The column <code>public.rhodecode_settings.app_settings_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord, java.lang.Integer> APP_SETTINGS_ID = createField("app_settings_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.rhodecode_settings.app_settings_name</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord, java.lang.String> APP_SETTINGS_NAME = createField("app_settings_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.rhodecode_settings.app_settings_value</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord, java.lang.String> APP_SETTINGS_VALUE = createField("app_settings_value", org.jooq.impl.SQLDataType.VARCHAR.length(4096), this);

	/**
	 * The column <code>public.rhodecode_settings.app_settings_type</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord, java.lang.String> APP_SETTINGS_TYPE = createField("app_settings_type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>public.rhodecode_settings</code> table reference
	 */
	public RhodecodeSettings() {
		super("rhodecode_settings", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.rhodecode_settings</code> table reference
	 */
	public RhodecodeSettings(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.RhodecodeSettings.RHODECODE_SETTINGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_RHODECODE_SETTINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_SETTINGS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeSettingsRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_SETTINGS_PKEY, org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_SETTINGS_APP_SETTINGS_NAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.RhodecodeSettings as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.RhodecodeSettings(alias);
	}
}
