/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RhodecodeUi extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord> {

	private static final long serialVersionUID = -123439677;

	/**
	 * The singleton instance of <code>public.rhodecode_ui</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi RHODECODE_UI = new org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord.class;
	}

	/**
	 * The column <code>public.rhodecode_ui.ui_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.Integer> UI_ID = createField("ui_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.rhodecode_ui.ui_section</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.String> UI_SECTION = createField("ui_section", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.rhodecode_ui.ui_key</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.String> UI_KEY = createField("ui_key", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.rhodecode_ui.ui_value</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.String> UI_VALUE = createField("ui_value", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.rhodecode_ui.ui_active</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.Boolean> UI_ACTIVE = createField("ui_active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.rhodecode_ui</code> table reference
	 */
	public RhodecodeUi() {
		super("rhodecode_ui", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.rhodecode_ui</code> table reference
	 */
	public RhodecodeUi(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_RHODECODE_UI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_UI_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_UI_PKEY, org.rhodecode.ldap.sync.jooq.Keys.RHODECODE_UI_UI_KEY_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi(alias);
	}
}
