/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupUserGroupToPerm extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord> {

	private static final long serialVersionUID = 1625036103;

	/**
	 * The singleton instance of <code>public.user_group_user_group_to_perm</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UserGroupUserGroupToPerm USER_GROUP_USER_GROUP_TO_PERM = new org.rhodecode.ldap.sync.jooq.tables.UserGroupUserGroupToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord.class;
	}

	/**
	 * The column <code>public.user_group_user_group_to_perm.user_group_user_group_to_perm_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, java.lang.Integer> USER_GROUP_USER_GROUP_TO_PERM_ID = createField("user_group_user_group_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_group_user_group_to_perm.target_user_group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, java.lang.Integer> TARGET_USER_GROUP_ID = createField("target_user_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_group_user_group_to_perm.permission_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_group_user_group_to_perm.user_group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, java.lang.Integer> USER_GROUP_ID = createField("user_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.user_group_user_group_to_perm</code> table reference
	 */
	public UserGroupUserGroupToPerm() {
		super("user_group_user_group_to_perm", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_group_user_group_to_perm</code> table reference
	 */
	public UserGroupUserGroupToPerm(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UserGroupUserGroupToPerm.USER_GROUP_USER_GROUP_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USER_GROUP_USER_GROUP_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM_PKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM_TARGET_USER_GROUP_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserGroupUserGroupToPermRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM__USER_GROUP_USER_GROUP_TO_PERM_TARGET_USER_GROUP_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM__USER_GROUP_USER_GROUP_TO_PERM_PERMISSION_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_GROUP_USER_GROUP_TO_PERM__USER_GROUP_USER_GROUP_TO_PERM_USER_GROUP_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UserGroupUserGroupToPerm as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UserGroupUserGroupToPerm(alias);
	}
}
