/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersGroupRepoGroupToPerm extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord> {

	private static final long serialVersionUID = -1126923466;

	/**
	 * The singleton instance of <code>public.users_group_repo_group_to_perm</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm USERS_GROUP_REPO_GROUP_TO_PERM = new org.rhodecode.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord.class;
	}

	/**
	 * The column <code>public.users_group_repo_group_to_perm.users_group_repo_group_to_perm_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, java.lang.Integer> USERS_GROUP_REPO_GROUP_TO_PERM_ID = createField("users_group_repo_group_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.users_group_repo_group_to_perm.users_group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, java.lang.Integer> USERS_GROUP_ID = createField("users_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.users_group_repo_group_to_perm.group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, java.lang.Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.users_group_repo_group_to_perm.permission_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.users_group_repo_group_to_perm</code> table reference
	 */
	public UsersGroupRepoGroupToPerm() {
		super("users_group_repo_group_to_perm", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.users_group_repo_group_to_perm</code> table reference
	 */
	public UsersGroupRepoGroupToPerm(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm.USERS_GROUP_REPO_GROUP_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USERS_GROUP_REPO_GROUP_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM_PKEY, org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM_USERS_GROUP_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupRepoGroupToPermRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM__USERS_GROUP_REPO_GROUP_TO_PERM_USERS_GROUP_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM__USERS_GROUP_REPO_GROUP_TO_PERM_GROUP_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUP_REPO_GROUP_TO_PERM__USERS_GROUP_REPO_GROUP_TO_PERM_PERMISSION_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UsersGroupRepoGroupToPerm(alias);
	}
}
