/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersGroupsMembers extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord> {

	private static final long serialVersionUID = -1117434513;

	/**
	 * The singleton instance of <code>public.users_groups_members</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers USERS_GROUPS_MEMBERS = new org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord.class;
	}

	/**
	 * The column <code>public.users_groups_members.users_group_member_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, java.lang.Integer> USERS_GROUP_MEMBER_ID = createField("users_group_member_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.users_groups_members.users_group_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, java.lang.Integer> USERS_GROUP_ID = createField("users_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.users_groups_members.user_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.users_groups_members</code> table reference
	 */
	public UsersGroupsMembers() {
		super("users_groups_members", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.users_groups_members</code> table reference
	 */
	public UsersGroupsMembers(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USERS_GROUPS_MEMBERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUPS_MEMBERS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUPS_MEMBERS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUPS_MEMBERS__USERS_GROUPS_MEMBERS_USERS_GROUP_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USERS_GROUPS_MEMBERS__USERS_GROUPS_MEMBERS_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers(alias);
	}
}
