/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRepoGroupToPerm extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord> {

	private static final long serialVersionUID = -19298862;

	/**
	 * The singleton instance of <code>public.user_repo_group_to_perm</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UserRepoGroupToPerm USER_REPO_GROUP_TO_PERM = new org.rhodecode.ldap.sync.jooq.tables.UserRepoGroupToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord.class;
	}

	/**
	 * The column <code>public.user_repo_group_to_perm.group_to_perm_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, java.lang.Integer> GROUP_TO_PERM_ID = createField("group_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_repo_group_to_perm.user_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_repo_group_to_perm.group_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, java.lang.Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_repo_group_to_perm.permission_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.user_repo_group_to_perm</code> table reference
	 */
	public UserRepoGroupToPerm() {
		super("user_repo_group_to_perm", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_repo_group_to_perm</code> table reference
	 */
	public UserRepoGroupToPerm(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UserRepoGroupToPerm.USER_REPO_GROUP_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USER_REPO_GROUP_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM_PKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM_USER_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserRepoGroupToPermRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM__USER_REPO_GROUP_TO_PERM_USER_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM__USER_REPO_GROUP_TO_PERM_GROUP_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_REPO_GROUP_TO_PERM__USER_REPO_GROUP_TO_PERM_PERMISSION_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UserRepoGroupToPerm as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UserRepoGroupToPerm(alias);
	}
}
