/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToNotification extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord> {

	private static final long serialVersionUID = -1213836960;

	/**
	 * The singleton instance of <code>public.user_to_notification</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UserToNotification USER_TO_NOTIFICATION = new org.rhodecode.ldap.sync.jooq.tables.UserToNotification();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord.class;
	}

	/**
	 * The column <code>public.user_to_notification.user_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_to_notification.notification_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, java.lang.Integer> NOTIFICATION_ID = createField("notification_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_to_notification.read</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, java.lang.Boolean> READ = createField("read", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The column <code>public.user_to_notification.sent_on</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, java.sql.Timestamp> SENT_ON = createField("sent_on", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>public.user_to_notification</code> table reference
	 */
	public UserToNotification() {
		super("user_to_notification", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_to_notification</code> table reference
	 */
	public UserToNotification(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USER_TO_NOTIFICATION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_TO_NOTIFICATION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_TO_NOTIFICATION__USER_TO_NOTIFICATION_USER_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_TO_NOTIFICATION__USER_TO_NOTIFICATION_NOTIFICATION_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UserToNotification as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UserToNotification(alias);
	}
}
