/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserUserGroupToPerm extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord> {

	private static final long serialVersionUID = 1685598842;

	/**
	 * The singleton instance of <code>public.user_user_group_to_perm</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UserUserGroupToPerm USER_USER_GROUP_TO_PERM = new org.rhodecode.ldap.sync.jooq.tables.UserUserGroupToPerm();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord.class;
	}

	/**
	 * The column <code>public.user_user_group_to_perm.user_user_group_to_perm_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, java.lang.Integer> USER_USER_GROUP_TO_PERM_ID = createField("user_user_group_to_perm_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_user_group_to_perm.user_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_user_group_to_perm.permission_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, java.lang.Integer> PERMISSION_ID = createField("permission_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>public.user_user_group_to_perm.user_group_id</code>. 
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, java.lang.Integer> USER_GROUP_ID = createField("user_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>public.user_user_group_to_perm</code> table reference
	 */
	public UserUserGroupToPerm() {
		super("user_user_group_to_perm", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_user_group_to_perm</code> table reference
	 */
	public UserUserGroupToPerm(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UserUserGroupToPerm.USER_USER_GROUP_TO_PERM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USER_USER_GROUP_TO_PERM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM_PKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM_USER_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserUserGroupToPermRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM__USER_USER_GROUP_TO_PERM_USER_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM__USER_USER_GROUP_TO_PERM_PERMISSION_ID_FKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_USER_GROUP_TO_PERM__USER_USER_GROUP_TO_PERM_USER_GROUP_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UserUserGroupToPerm as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UserUserGroupToPerm(alias);
	}
}
