/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserIpMap extends org.jooq.impl.TableImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord> {

	private static final long serialVersionUID = -1827631935;

	/**
	 * The singleton instance of <code>public.user_ip_map</code>
	 */
	public static final org.rhodecode.ldap.sync.jooq.tables.UserIpMap USER_IP_MAP = new org.rhodecode.ldap.sync.jooq.tables.UserIpMap();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord> getRecordType() {
		return org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord.class;
	}

	/**
	 * The column <code>public.user_ip_map.ip_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, java.lang.Integer> IP_ID = createField("ip_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * The column <code>public.user_ip_map.user_id</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>public.user_ip_map.ip_addr</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, java.lang.String> IP_ADDR = createField("ip_addr", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>public.user_ip_map.active</code>.
	 */
	public final org.jooq.TableField<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, java.lang.Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * Create a <code>public.user_ip_map</code> table reference
	 */
	public UserIpMap() {
		super("user_ip_map", org.rhodecode.ldap.sync.jooq.Public.PUBLIC);
	}

	/**
	 * Create an aliased <code>public.user_ip_map</code> table reference
	 */
	public UserIpMap(java.lang.String alias) {
		super(alias, org.rhodecode.ldap.sync.jooq.Public.PUBLIC, org.rhodecode.ldap.sync.jooq.tables.UserIpMap.USER_IP_MAP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, java.lang.Integer> getIdentity() {
		return org.rhodecode.ldap.sync.jooq.Keys.IDENTITY_USER_IP_MAP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord> getPrimaryKey() {
		return org.rhodecode.ldap.sync.jooq.Keys.USER_IP_MAP_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_IP_MAP_PKEY, org.rhodecode.ldap.sync.jooq.Keys.USER_IP_MAP_USER_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.rhodecode.ldap.sync.jooq.tables.records.UserIpMapRecord, ?>>asList(org.rhodecode.ldap.sync.jooq.Keys.USER_IP_MAP__USER_IP_MAP_USER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.rhodecode.ldap.sync.jooq.tables.UserIpMap as(java.lang.String alias) {
		return new org.rhodecode.ldap.sync.jooq.tables.UserIpMap(alias);
	}
}
