/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangesetCommentsRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.ChangesetCommentsRecord> implements org.jooq.Record11<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 1634817468;

	/**
	 * Setter for <code>public.changeset_comments.comment_id</code>. 
	 */
	public void setCommentId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.comment_id</code>. 
	 */
	public java.lang.Integer getCommentId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.changeset_comments.repo_id</code>. 
	 */
	public void setRepoId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.repo_id</code>. 
	 */
	public java.lang.Integer getRepoId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.changeset_comments.revision</code>. 
	 */
	public void setRevision(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.revision</code>. 
	 */
	public java.lang.String getRevision() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.changeset_comments.pull_request_id</code>. 
	 */
	public void setPullRequestId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.pull_request_id</code>. 
	 */
	public java.lang.Integer getPullRequestId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.changeset_comments.line_no</code>. 
	 */
	public void setLineNo(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.line_no</code>. 
	 */
	public java.lang.String getLineNo() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.changeset_comments.hl_lines</code>. 
	 */
	public void setHlLines(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.hl_lines</code>. 
	 */
	public java.lang.String getHlLines() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.changeset_comments.f_path</code>. 
	 */
	public void setFPath(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.f_path</code>. 
	 */
	public java.lang.String getFPath() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.changeset_comments.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.changeset_comments.text</code>. 
	 */
	public void setText(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.text</code>. 
	 */
	public java.lang.String getText() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.changeset_comments.created_on</code>. 
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.created_on</code>. 
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>public.changeset_comments.modified_at</code>. 
	 */
	public void setModifiedAt(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.changeset_comments.modified_at</code>. 
	 */
	public java.sql.Timestamp getModifiedAt() {
		return (java.sql.Timestamp) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.COMMENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.REPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.REVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.PULL_REQUEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.LINE_NO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.HL_LINES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.F_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.TEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS.MODIFIED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getCommentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRepoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getRevision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPullRequestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLineNo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getHlLines();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getFPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getText();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getModifiedAt();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ChangesetCommentsRecord
	 */
	public ChangesetCommentsRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS);
	}

	/**
	 * Create a detached, initialised ChangesetCommentsRecord
	 */
	public ChangesetCommentsRecord(java.lang.Integer commentId, java.lang.Integer repoId, java.lang.String revision, java.lang.Integer pullRequestId, java.lang.String lineNo, java.lang.String hlLines, java.lang.String fPath, java.lang.Integer userId, java.lang.String text, java.sql.Timestamp createdOn, java.sql.Timestamp modifiedAt) {
		super(org.rhodecode.ldap.sync.jooq.tables.ChangesetComments.CHANGESET_COMMENTS);

		setValue(0, commentId);
		setValue(1, repoId);
		setValue(2, revision);
		setValue(3, pullRequestId);
		setValue(4, lineNo);
		setValue(5, hlLines);
		setValue(6, fPath);
		setValue(7, userId);
		setValue(8, text);
		setValue(9, createdOn);
		setValue(10, modifiedAt);
	}
}
