/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GistsRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.GistsRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = 515419613;

	/**
	 * Setter for <code>public.gists.gist_id</code>. 
	 */
	public void setGistId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.gists.gist_id</code>. 
	 */
	public java.lang.Integer getGistId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.gists.gist_access_id</code>. 
	 */
	public void setGistAccessId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.gists.gist_access_id</code>. 
	 */
	public java.lang.String getGistAccessId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.gists.gist_description</code>. 
	 */
	public void setGistDescription(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.gists.gist_description</code>. 
	 */
	public java.lang.String getGistDescription() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.gists.user_id</code>. 
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.gists.user_id</code>. 
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.gists.gist_expires</code>. 
	 */
	public void setGistExpires(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.gists.gist_expires</code>. 
	 */
	public java.lang.Double getGistExpires() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>public.gists.gist_type</code>. 
	 */
	public void setGistType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.gists.gist_type</code>. 
	 */
	public java.lang.String getGistType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.gists.created_on</code>. 
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.gists.created_on</code>. 
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>public.gists.modified_at</code>. 
	 */
	public void setModifiedAt(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.gists.modified_at</code>. 
	 */
	public java.sql.Timestamp getModifiedAt() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Double, java.lang.String, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.GIST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.GIST_ACCESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.GIST_DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.GIST_EXPIRES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.GIST_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS.MODIFIED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getGistId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGistAccessId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getGistDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getGistExpires();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getGistType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreatedOn();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getModifiedAt();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GistsRecord
	 */
	public GistsRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS);
	}

	/**
	 * Create a detached, initialised GistsRecord
	 */
	public GistsRecord(java.lang.Integer gistId, java.lang.String gistAccessId, java.lang.String gistDescription, java.lang.Integer userId, java.lang.Double gistExpires, java.lang.String gistType, java.sql.Timestamp createdOn, java.sql.Timestamp modifiedAt) {
		super(org.rhodecode.ldap.sync.jooq.tables.Gists.GISTS);

		setValue(0, gistId);
		setValue(1, gistAccessId);
		setValue(2, gistDescription);
		setValue(3, userId);
		setValue(4, gistExpires);
		setValue(5, gistType);
		setValue(6, createdOn);
		setValue(7, modifiedAt);
	}
}
