/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RepositoriesFieldsRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.RepositoriesFieldsRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = 1549790414;

	/**
	 * Setter for <code>public.repositories_fields.repo_field_id</code>. 
	 */
	public void setRepoFieldId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.repo_field_id</code>. 
	 */
	public java.lang.Integer getRepoFieldId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.repositories_fields.repository_id</code>. 
	 */
	public void setRepositoryId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.repository_id</code>. 
	 */
	public java.lang.Integer getRepositoryId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.repositories_fields.field_key</code>. 
	 */
	public void setFieldKey(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.field_key</code>. 
	 */
	public java.lang.String getFieldKey() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.repositories_fields.field_label</code>. 
	 */
	public void setFieldLabel(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.field_label</code>. 
	 */
	public java.lang.String getFieldLabel() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.repositories_fields.field_value</code>. 
	 */
	public void setFieldValue(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.field_value</code>. 
	 */
	public java.lang.String getFieldValue() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.repositories_fields.field_desc</code>. 
	 */
	public void setFieldDesc(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.field_desc</code>. 
	 */
	public java.lang.String getFieldDesc() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.repositories_fields.field_type</code>. 
	 */
	public void setFieldType(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.field_type</code>. 
	 */
	public java.lang.String getFieldType() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.repositories_fields.created_on</code>. 
	 */
	public void setCreatedOn(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.repositories_fields.created_on</code>. 
	 */
	public java.sql.Timestamp getCreatedOn() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.REPO_FIELD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.REPOSITORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.FIELD_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.FIELD_LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.FIELD_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.FIELD_DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.FIELD_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS.CREATED_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRepoFieldId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRepositoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFieldKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getFieldLabel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFieldValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFieldDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getFieldType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getCreatedOn();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RepositoriesFieldsRecord
	 */
	public RepositoriesFieldsRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS);
	}

	/**
	 * Create a detached, initialised RepositoriesFieldsRecord
	 */
	public RepositoriesFieldsRecord(java.lang.Integer repoFieldId, java.lang.Integer repositoryId, java.lang.String fieldKey, java.lang.String fieldLabel, java.lang.String fieldValue, java.lang.String fieldDesc, java.lang.String fieldType, java.sql.Timestamp createdOn) {
		super(org.rhodecode.ldap.sync.jooq.tables.RepositoriesFields.REPOSITORIES_FIELDS);

		setValue(0, repoFieldId);
		setValue(1, repositoryId);
		setValue(2, fieldKey);
		setValue(3, fieldLabel);
		setValue(4, fieldValue);
		setValue(5, fieldDesc);
		setValue(6, fieldType);
		setValue(7, createdOn);
	}
}
