/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RhodecodeUiRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.RhodecodeUiRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = -1052379801;

	/**
	 * Setter for <code>public.rhodecode_ui.ui_id</code>. 
	 */
	public void setUiId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.rhodecode_ui.ui_id</code>. 
	 */
	public java.lang.Integer getUiId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.rhodecode_ui.ui_section</code>. 
	 */
	public void setUiSection(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.rhodecode_ui.ui_section</code>. 
	 */
	public java.lang.String getUiSection() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.rhodecode_ui.ui_key</code>. 
	 */
	public void setUiKey(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.rhodecode_ui.ui_key</code>. 
	 */
	public java.lang.String getUiKey() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.rhodecode_ui.ui_value</code>. 
	 */
	public void setUiValue(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.rhodecode_ui.ui_value</code>. 
	 */
	public java.lang.String getUiValue() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.rhodecode_ui.ui_active</code>. 
	 */
	public void setUiActive(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.rhodecode_ui.ui_active</code>. 
	 */
	public java.lang.Boolean getUiActive() {
		return (java.lang.Boolean) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI.UI_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI.UI_SECTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI.UI_KEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI.UI_VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI.UI_ACTIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUiId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUiSection();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUiKey();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getUiValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getUiActive();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RhodecodeUiRecord
	 */
	public RhodecodeUiRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI);
	}

	/**
	 * Create a detached, initialised RhodecodeUiRecord
	 */
	public RhodecodeUiRecord(java.lang.Integer uiId, java.lang.String uiSection, java.lang.String uiKey, java.lang.String uiValue, java.lang.Boolean uiActive) {
		super(org.rhodecode.ldap.sync.jooq.tables.RhodecodeUi.RHODECODE_UI);

		setValue(0, uiId);
		setValue(1, uiSection);
		setValue(2, uiKey);
		setValue(3, uiValue);
		setValue(4, uiActive);
	}
}
