/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatisticsRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.StatisticsRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], byte[], byte[]> {

	private static final long serialVersionUID = 207377994;

	/**
	 * Setter for <code>public.statistics.stat_id</code>. 
	 */
	public void setStatId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.statistics.stat_id</code>. 
	 */
	public java.lang.Integer getStatId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.statistics.repository_id</code>. 
	 */
	public void setRepositoryId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.statistics.repository_id</code>. 
	 */
	public java.lang.Integer getRepositoryId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.statistics.stat_on_revision</code>. 
	 */
	public void setStatOnRevision(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.statistics.stat_on_revision</code>. 
	 */
	public java.lang.Integer getStatOnRevision() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.statistics.commit_activity</code>. 
	 */
	public void setCommitActivity(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.statistics.commit_activity</code>. 
	 */
	public byte[] getCommitActivity() {
		return (byte[]) getValue(3);
	}

	/**
	 * Setter for <code>public.statistics.commit_activity_combined</code>. 
	 */
	public void setCommitActivityCombined(byte[] value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.statistics.commit_activity_combined</code>. 
	 */
	public byte[] getCommitActivityCombined() {
		return (byte[]) getValue(4);
	}

	/**
	 * Setter for <code>public.statistics.languages</code>. 
	 */
	public void setLanguages(byte[] value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.statistics.languages</code>. 
	 */
	public byte[] getLanguages() {
		return (byte[]) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], byte[], byte[]> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.Integer, java.lang.Integer, byte[], byte[], byte[]> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.STAT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.REPOSITORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.STAT_ON_REVISION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.COMMIT_ACTIVITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.COMMIT_ACTIVITY_COMBINED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field6() {
		return org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS.LANGUAGES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getStatId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRepositoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getStatOnRevision();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getCommitActivity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value5() {
		return getCommitActivityCombined();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value6() {
		return getLanguages();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StatisticsRecord
	 */
	public StatisticsRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS);
	}

	/**
	 * Create a detached, initialised StatisticsRecord
	 */
	public StatisticsRecord(java.lang.Integer statId, java.lang.Integer repositoryId, java.lang.Integer statOnRevision, byte[] commitActivity, byte[] commitActivityCombined, byte[] languages) {
		super(org.rhodecode.ldap.sync.jooq.tables.Statistics.STATISTICS);

		setValue(0, statId);
		setValue(1, repositoryId);
		setValue(2, statOnRevision);
		setValue(3, commitActivity);
		setValue(4, commitActivityCombined);
		setValue(5, languages);
	}
}
