/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersGroupsMembersRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.UsersGroupsMembersRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1784351550;

	/**
	 * Setter for <code>public.users_groups_members.users_group_member_id</code>.
	 */
	public void setUsersGroupMemberId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.users_groups_members.users_group_member_id</code>.
	 */
	public java.lang.Integer getUsersGroupMemberId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.users_groups_members.users_group_id</code>.
	 */
	public void setUsersGroupId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.users_groups_members.users_group_id</code>.
	 */
	public java.lang.Integer getUsersGroupId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.users_groups_members.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.users_groups_members.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS.USERS_GROUP_MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS.USERS_GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUsersGroupMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUsersGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getUserId();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersGroupsMembersRecord
	 */
	public UsersGroupsMembersRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS);
	}

	/**
	 * Create a detached, initialised UsersGroupsMembersRecord
	 */
	public UsersGroupsMembersRecord(java.lang.Integer usersGroupMemberId, java.lang.Integer usersGroupId, java.lang.Integer userId) {
		super(org.rhodecode.ldap.sync.jooq.tables.UsersGroupsMembers.USERS_GROUPS_MEMBERS);

		setValue(0, usersGroupMemberId);
		setValue(1, usersGroupId);
		setValue(2, userId);
	}
}
