/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToNotificationRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserToNotificationRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.sql.Timestamp> {

	private static final long serialVersionUID = 198458826;

	/**
	 * Setter for <code>public.user_to_notification.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_to_notification.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.user_to_notification.notification_id</code>.
	 */
	public void setNotificationId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_to_notification.notification_id</code>.
	 */
	public java.lang.Integer getNotificationId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.user_to_notification.read</code>.
	 */
	public void setRead(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_to_notification.read</code>.
	 */
	public java.lang.Boolean getRead() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.user_to_notification.sent_on</code>.
	 */
	public void setSentOn(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.user_to_notification.sent_on</code>.
	 */
	public java.sql.Timestamp getSentOn() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Boolean, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION.NOTIFICATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION.READ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION.SENT_ON;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNotificationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getRead();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getSentOn();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserToNotificationRecord
	 */
	public UserToNotificationRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION);
	}

	/**
	 * Create a detached, initialised UserToNotificationRecord
	 */
	public UserToNotificationRecord(java.lang.Integer userId, java.lang.Integer notificationId, java.lang.Boolean read, java.sql.Timestamp sentOn) {
		super(org.rhodecode.ldap.sync.jooq.tables.UserToNotification.USER_TO_NOTIFICATION);

		setValue(0, userId);
		setValue(1, notificationId);
		setValue(2, read);
		setValue(3, sentOn);
	}
}
