/**
 * This class is generated by jOOQ
 */
package org.rhodecode.ldap.sync.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.7" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserLogsRecord extends org.jooq.impl.UpdatableRecordImpl<org.rhodecode.ldap.sync.jooq.tables.records.UserLogsRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -965108108;

	/**
	 * Setter for <code>public.user_logs.user_log_id</code>.
	 */
	public void setUserLogId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user_logs.user_log_id</code>.
	 */
	public java.lang.Integer getUserLogId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.user_logs.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user_logs.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.user_logs.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user_logs.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.user_logs.repository_id</code>.
	 */
	public void setRepositoryId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.user_logs.repository_id</code>.
	 */
	public java.lang.Integer getRepositoryId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.user_logs.repository_name</code>.
	 */
	public void setRepositoryName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.user_logs.repository_name</code>.
	 */
	public java.lang.String getRepositoryName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.user_logs.user_ip</code>.
	 */
	public void setUserIp(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.user_logs.user_ip</code>.
	 */
	public java.lang.String getUserIp() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.user_logs.action</code>.
	 */
	public void setAction(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.user_logs.action</code>.
	 */
	public java.lang.String getAction() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.user_logs.action_date</code>.
	 */
	public void setActionDate(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.user_logs.action_date</code>.
	 */
	public java.sql.Timestamp getActionDate() {
		return (java.sql.Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.USER_LOG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.REPOSITORY_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.REPOSITORY_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.USER_IP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.ACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS.ACTION_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getUserLogId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getRepositoryId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getRepositoryName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getUserIp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getAction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getActionDate();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserLogsRecord
	 */
	public UserLogsRecord() {
		super(org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS);
	}

	/**
	 * Create a detached, initialised UserLogsRecord
	 */
	public UserLogsRecord(java.lang.Integer userLogId, java.lang.Integer userId, java.lang.String username, java.lang.Integer repositoryId, java.lang.String repositoryName, java.lang.String userIp, java.lang.String action, java.sql.Timestamp actionDate) {
		super(org.rhodecode.ldap.sync.jooq.tables.UserLogs.USER_LOGS);

		setValue(0, userLogId);
		setValue(1, userId);
		setValue(2, username);
		setValue(3, repositoryId);
		setValue(4, repositoryName);
		setValue(5, userIp);
		setValue(6, action);
		setValue(7, actionDate);
	}
}
